const std = @import("std");

const atomic_counter = @import("node/atomic_counter.zig");
const credential = @import("node/credential.zig");
const mutex = @import("node/mutex.zig");
const shared_ptr = @import("node/shared_ptr.zig");
const ring_buffer = @import("node/ring_buffer.zig");
const buffer = @import("node/buffer.zig");
const hashtable = @import("node/hashtable.zig");
const metrics = @import("node/metrics.zig");
const constants = @import("node/constants.zig");
const utils = @import("node/utils.zig");
const sha512 = @import("node/sha512.zig");
const poly1305 = @import("node/poly1305.zig");
const salsa20 = @import("node/salsa20.zig");
const ecc = @import("node/ecc.zig");
const aes = @import("node/aes.zig");
const address = @import("node/address.zig");
const mac = @import("node/mac.zig");
const inet_address = @import("node/inet_address.zig");
const multicast_group = @import("node/multicast_group.zig");
const dns = @import("node/dns.zig");
const dictionary = @import("node/dictionary.zig");
const identity = @import("node/identity.zig");
const lz4 = @import("node/lz4.zig");
const packet = @import("node/packet.zig");
const tag = @import("node/tag.zig");
const revocation = @import("node/revocation.zig");
const certificate_of_membership = @import("node/certificate_of_membership.zig");
const certificate_of_ownership = @import("node/certificate_of_ownership.zig");
const capability = @import("node/capability.zig");
const world = @import("node/world.zig");
const runtime_environment = @import("node/runtime_environment.zig");
const network_config = @import("node/network_config.zig");
const network_controller = @import("node/network_controller.zig");
const path = @import("node/path.zig");
const trace = @import("node/trace.zig");
const self_awareness = @import("node/self_awareness.zig");
const network = @import("node/network.zig");
const incoming_packet = @import("node/incoming_packet.zig");
const node = @import("node/node.zig");

const test_salsa20_keystream_regression = @import("test_salsa20_keystream_regression.zig");
const test_expected_reply_regression = @import("test_expected_reply_regression.zig");
const test_fragment_reassembly_regression = @import("test_fragment_reassembly_regression.zig");
const test_bug_hunting_regression = @import("test_bug_hunting_regression.zig");

test {
    std.testing.refAllDecls(atomic_counter);
    std.testing.refAllDecls(credential);
    std.testing.refAllDecls(mutex);
    std.testing.refAllDecls(shared_ptr);
    std.testing.refAllDecls(ring_buffer);
    std.testing.refAllDecls(buffer);
    std.testing.refAllDecls(hashtable);
    std.testing.refAllDecls(metrics);
    std.testing.refAllDecls(constants);
    std.testing.refAllDecls(utils);
    std.testing.refAllDecls(sha512);
    std.testing.refAllDecls(poly1305);
    std.testing.refAllDecls(salsa20);
    std.testing.refAllDecls(ecc);
    std.testing.refAllDecls(aes);
    std.testing.refAllDecls(address);
    std.testing.refAllDecls(mac);
    std.testing.refAllDecls(inet_address);
    std.testing.refAllDecls(multicast_group);
    std.testing.refAllDecls(dns);
    std.testing.refAllDecls(dictionary);
    std.testing.refAllDecls(identity);
    std.testing.refAllDecls(lz4);
    std.testing.refAllDecls(packet);
    std.testing.refAllDecls(tag);
    std.testing.refAllDecls(revocation);
    std.testing.refAllDecls(certificate_of_membership);
    std.testing.refAllDecls(certificate_of_ownership);
    std.testing.refAllDecls(capability);
    std.testing.refAllDecls(world);
    std.testing.refAllDecls(runtime_environment);
    std.testing.refAllDecls(network_config);
    std.testing.refAllDecls(network_controller);
    std.testing.refAllDecls(path);
    std.testing.refAllDecls(trace);
    std.testing.refAllDecls(self_awareness);
    std.testing.refAllDecls(network);
    std.testing.refAllDecls(incoming_packet);
    std.testing.refAllDecls(node);
    std.testing.refAllDecls(test_salsa20_keystream_regression);
    std.testing.refAllDecls(test_expected_reply_regression);
    std.testing.refAllDecls(test_fragment_reassembly_regression);
    std.testing.refAllDecls(test_bug_hunting_regression);
}
